source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object', '~> 2.0'
gem 'data_magic'
gem 'site_prism', '2.12'
gem 'capybara', '2.18.0'
gem 'selenium-webdriver'
gem 'faker'
gem 'httparty'